# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Anaxago\CoreBundle\Entity\User:
            algorithm: bcrypt

    providers:
        anaxago_provider:
            entity:
                class: AnaxagoCoreBundle:User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
        main:
            provider: anaxago_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
            logout_on_user_change: true

        api:
            pattern:   ^/api/v[^/]+/secure
            stateless: true
            provider:  anaxago_provider
            lexik_jwt:
                authorization_header: # check token in Authorization Header
                    enabled: true
                    prefix:  Bearer
                cookie:               # check token in a cookie
                    enabled: false
                    name:    BEARER
                query_parameter:      # check token in query string parameter
                    enabled: true
                    name:    token
                throw_exceptions:        true     # When an authentication failure occurs, return a 401 response immediately
                create_entry_point:      true      # When no authentication details are provided, create a default entry point that returns a 401 response
                authentication_provider: lexik_jwt_authentication.security.authentication.provider
