anaxago_core_homepage:
    path:     /
    defaults: { _controller: AnaxagoCoreBundle:Default:index }

api_project_public:
  resource: "@AnaxagoCoreBundle/Controller/Api"
  type: annotation
  prefix: /api

api_project_private:
  resource: "@AnaxagoCoreBundle/Controller/Api/Secure"
  type: annotation
  prefix: /api/secure

api_login_check:
    path: /api/login_check
